// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  MultipleRequests = 2,
  Request = 3,
  HTTPMethod = 4,
  URL = 5,
  VERSION = 6,
  PathSegment = 7,
  Body = 8,
  Property = 9,
  Identifier = 10,
  Value = 11,
  String = 12,
  Number = 13,
  Boolean = 14,
  Array = 15
