// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  MultipleRequests = 2,
  Request = 3,
  HTTPMethod = 4,
  URL = 5,
  VERSION = 6,
  API = 7,
  PathSegment = 8,
  Body = 9,
  Property = 10,
  Identifier = 11,
  Value = 12,
  String = 13,
  Number = 14,
  Boolean = 15,
  Array = 16
