paths:
  /milvus/connect:
    post:
      tags:
        - Milvus
      description: Connect to milvus server
      requestBody:
        description: Milvus address
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - 'address'
              properties:
                address:
                  type: string
                  example: 127.0.0.1:19530
      responses:
        200:
          schema:
            type: object

  /milvus/disconnect:
    post:
      tags:
        - Milvus
      description: Disconnect to milvus server
      responses:
        200:
          schema:
            type: object

  /milvus/check:
    get:
      tags:
        - Milvus
      description: Check milvus alive or not.
      parameters:
        - in: query
          name: address
          description: Milvus address
      responses:
        200:
          schema:
            type: object

  /milvus/metrics:
    get:
      tags:
        - Milvus
      description: Get milvus metrics
      responses:
        200:
          schema:
            type: object

  /milvus/flush:
    post:
      tags:
        - Milvus
      description: Flush data in milvus
      requestBody:
        description: The collection names you want to flush
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - 'collection_names'
              properties:
                collection_names:
                  type: array
                  example: [collectionName]
      responses:
        200:
          schema:
            type: object
